### ISSUE TITLE
(Windows) Static compilation issues

### ISSUE THREAD

**Issue by rz5** [pcercuei/lightrec#1]
On Windows, I am compilling lightrec as a statically linked object instead of a DLL.
Due to how `lightrec.h` defines `__api` as either `__declspec("dllimport")` or  `__declspec("dllexport")`, I am getting warnings the while compiling `lightrec.c` related to these attributes, e.g.:
```Makefile
path/to/lightrec.c:692:5: warning: 'lightrec_execute' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
  692 | u32 lightrec_execute(struct lightrec_state *state, u32 pc, u32 target_cycle)

```

and afterwards I errors related to undeclared references to all the functions declared in `lightrec.h`, e.g.:

```Makefile
ld.exe: lightrec_user.o:lightrec_user.cpp:(.text+0x1ab1): undefined reference to `__imp_lightrec_execute'
```

_____

I can work around those errors by adding a new macro that changes how `__api`is defined for static compilation and defining it during compilation, like so:

```C
#ifndef lightrec_STATIC
#   ifdef _WIN32
#      ifdef lightrec_EXPORTS
#         define __api __declspec(dllexport)
#      else
#         define __api __declspec(dllimport)
#      endif
#   elif __GNUC__ >= 4
#      define __api __attribute__((visibility ("default")))
#   else
#      define __api
#   endif
#else
#   define __api
#endif
```

Because this works for me, it suggests the attributes - as warned by the compiler - are causing my linker errors. Perhaps the workaround should be part of the codebase? Or maybe the function definitions in `lightrec.c` also need matching attributes?

**Comment by pcercuei** [comment]
What about this:
```
#ifdef _WIN32
#   ifdef lightrec_EXPORTS
#	define __api __declspec(dllexport)
#   elif !defined(LIGHTREC_STATIC)
#	define __api __declspec(dllimport)
#   else
#	define __api
#   endif
#elif __GNUC__ >= 4
#   define __api __attribute__((visibility ("default")))
#else
#   define __api
#endif
```

Then in your app's Makefile you can add -DLIGHTREC_STATIC=1 to the CPPFLAGS and it should work.

**Comment by rz5** [comment]
@pcercuei - Yup, that works too.
