### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by padremayi** [pcercuei/lightrec#12]
Hi, is there any tip on how to use your library within other application?

**Comment by pcercuei** [comment]
Hi,

There is no wiki. The best way is to look at how other programs use it.

For instance: https://github.com/pcercuei/pcsx4all/blob/master/src/recompiler/lightrec/lightrec.cpp

**Comment by padremayi** [comment]
It is very difficult in this way.

Thanks for your tip
