### ISSUE TITLE
Any chance for port Lightrec to WiiSXRX/WiiStation?

### ISSUE THREAD

**Issue by saulfabregwiivc** [pcercuei/lightrec#18]
So, i've saw your work at this (very old but still maintained) PlayStation 1 emulator for Wii, WiiSX (formerly PCSXGC), that you implemented Lightrec: https://github.com/pcercuei/pcsxgc/tree/lightrec

I was going to ask...
Since WiiSXRX (https://github.com/niuus/WiiSXRX) and WiiStation (formerly WiiSXRX_2022, https://github.com/xjsxjs197/WiiSXRX_2022) are both much better emulators of PS1 for Wii than the old PCSXGC, i was going to ask if you could try implementing your Lightrec to these PS1 emulators for Wii?

Thanks for your great work, it's so appreciated ;)

**Comment by pcercuei** [comment]
How are these much better than WiiSX?

**Comment by saulfabregwiivc** [comment]
@pcercuei 

WiiStation and WiiSXRX have much better compatibility with PS1 games than WiiSX.
There are games that doesn't run on WiiSX but on WiiStation/WiiSXRX.

**Comment by pcercuei** [comment]
Well I doubt it. We updated the core to the latest one from https://github.com/notaz/pcsx_rearmed, so the compatibility should be pretty good.

**Comment by saulfabregwiivc** [comment]
Hm.
Quite interesting.
But i see Lightrec is much lighter than many current dynarecs on PS1 emulators, so i was wondering if you could carry your Lightrec modified from WiiSX to WiiStation/WiiSXRX?

I'm pretty sure with your Lightrec these will have a good speed performance while maintaing good compatibility.

**Comment by saulfabregwiivc** [comment]
Oh, and I also forgot to ask, where and how I can install and use your Lightrec library to devkitPro/devkitPPC for compiling for PowerPC (GameCube, Wii)? I'm trying to compile your branch of WiiSX with Lightrec with no success.

Also, how i can install the other libraries you tell in the makefile for WiiSX (`-llightrec -llightning -lopcodes -lbfd -liberty -lz`)? Sorry I'm new on compiling stuff on Wii and i don't know much about libraries used on the Wii (devkitPPC)

**Comment by pcercuei** [comment]
I don't see the point in working on three extremely similar PSX emulators. So I'll just work on one, and you can feel free to adapt my work on the other ones.

**Comment by pcercuei** [comment]
GNU Lightning / Lightrec build
===

Make sure you have access rights to the devkitpro toolchain, otherwise installing the files and libraries will fail.
If needed, you can run these scripts as root.

Build GNU Lightning
---

```
git clone https://git.savannah.gnu.org/git/lightning.git
cd lightning

export PATH=$PATH:/opt/devkitpro/devkitPPC/bin/

./bootstrap
./configure --host=powerpc-eabi --prefix=/ --enable-static --disable-shared

DESTDIR=/opt/devkitpro/devkitPPC/powerpc-eabi make -C lib install
DESTDIR=/opt/devkitpro/devkitPPC/powerpc-eabi make -C include install
```

Build Lightrec
---

```
git clone https://github.com/pcercuei/lightrec.git
mkdir -p lightrec/build
cd lightrec/build

export PATH=$PATH:/opt/devkitpro/devkitPPC/bin/

cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitPPC.cmake -DCMAKE_INSTALL_PREFIX= ..

DESTDIR=/opt/devkitpro/devkitPPC/powerpc-eabi make install
```

Build CubeSX
---

```
git clone https://github.com/pcercuei/pcsxgc.git -b lightrec
cd pcsxgc/Gamecube

make -f Makefile_Cube_Lightrec
```

**Comment by saulfabregwiivc** [comment]
Thanks for the compiling info, i will give a try.
Sad that you won't work in that for WiiSXRX/WiiStation, but happy i can try to implement Lightrec in those.
Closing.

**Comment by saulfabregwiivc** [comment]
I'm stuck at this part:

> ## Build Lightrec

> ```
> cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitPPC.cmake -DCMAKE_INSTALL_PREFIX= ..
> DESTDIR=/opt/devkitpro/devkitPPC/powerpc-eabi make install
> ```

I did make the cmake command, and when i tried to run make install for build and install Lightrec, it throws me this error:

`make: *** No rule to make target 'install'.  Stop.`

Does Lightrec have a Makefile like GNU Lightning? How i can fix that problem? Thanks ;)

**Comment by pcercuei** [comment]
What did the cmake output say?

**Comment by saulfabregwiivc** [comment]
> What did the cmake output say?

Forgot to mention, i'm not using CMake (through I have installed that for compile it). I'm compiling using MSys2 included with devkitPro.

And that error appears. Any fix?

**Comment by saulfabregwiivc** [comment]
I forgot to mention again, i'm not using Linux/Unix, i'm a Windows user. Maybe this is the problem? Any workaround for compile this when on Windows?

**Comment by saulfabregwiivc** [comment]
Here's a screenshot of what i get when i try to compile Lightrec:

![image](https://user-images.githubusercontent.com/66485640/216735854-93ab0529-a08b-419d-bd31-fcad2ac09da8.png)

**Comment by saulfabregwiivc** [comment]
Nevermind, i've figured out what's going on.

Before doing all the steps you told me, i had to do those things:

1. Install Git for Windows https://gitforwindows.org/
2. Install CMake https://cmake.org/
3. Restart your PC
4. On MSys2, run `pacman -Syyuu` a few times for install everything you need for compile this thing.
5. Close the MSys2, reopen it, and do the previous steps again for compile GNU Lightning and Lightrec.

Thanks anyways for helping, closing this again.

**Comment by saulfabregwiivc** [comment]
I've compiled the CubeSX with Lightrec successfully, but what can I do for compile the Wii version (WiiSX) with Lightrec?
Trying to compile for Wii throws:
```
PadWiiSX.c
In file included from C:/devkitPro/libogc/include/gccore.h:76,
                 from C:/Users/ASUS/pcsxgc/Gamecube/gc_input/controller.h:31,
                 from C:/Users/ASUS/pcsxgc/Gamecube/PadWiiSX.c:30:
C:/devkitPro/libogc/include/ogc/usbstorage.h:44:9: error: unknown type name 'syswd_t'
   44 |         syswd_t alarm;
      |         ^~~~~~~
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:18: PadWiiSX.o] Error 1
make: *** [Makefile_Wii:111: build] Error 2
```

EDIT: I compiled WiiSX by emukidid before the Lightrec changes and it compiles fine, maybe Lightrec on Wii isn't finished?

**Comment by pcercuei** [comment]
I only compile on Linux for the gamecube, for anything else you're on your own.

**Comment by pcercuei** [comment]
@saulfabregwiivc btw, pass `-DLOG_LEVEL=Warning` to cmake to silence the stats that Lightrec prints every few seconds.

**Comment by saulfabregwiivc** [comment]
> @saulfabregwiivc btw, pass `-DLOG_LEVEL=Warning` to cmake to silence the stats that Lightrec prints every few seconds.

Thanks for the info. I was going to ask if it was possible to remove the nasty messages that disturbs gameplay when on WiiSX/CubeSX with Lightrec, lol

**Comment by saulfabregwiivc** [comment]
only for reference and not forget:

Wii does not support pthread, and trying to compile with it will error, so you have to add `-DENABLE_THREADED_COMPILER=0` when using the CMake command. it should be:

`cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitPPC.cmake -DCMAKE_INSTALL_PREFIX= .. -DENABLE_THREADED_COMPILER=0`

for NoLog (don't throw any Lightrec log), use this:

`cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/devkitPPC.cmake -DCMAKE_INSTALL_PREFIX= .. -DENABLE_THREADED_COMPILER=0 -DLOG_LEVEL=NoLog`
