### ISSUE TITLE
Assertion in lightning due to change in lightrec

### ISSUE THREAD

**Issue by ZachCook** [pcercuei/lightrec#2]
When building lightning with --enable-assertions, upon starting emulator using lightrec (tried beetle and pcsx_rearmed):

> lightning/lib/lightning.c:2126: _jit_trampoline: Assertion `_jitc->tail && _jitc->tail->code == jit_code_prolog' failed.

Tried to bisect but had many skips due to segfaults:

>There are only 'skip'ped commits left to test.
The first bad commit could be any of:
4e6308beaf2c73e74fb4b319deccb807c3a6d575
53fd0e132e90fe2d21a76c412a0bf904a6a054e5
2d4318610ae10633439611023aeae42e80d23356
8c9b3b2b1521ea67b1b1e95a390de6815325a36b
627b913254a5f63d6f4406c0f4e8d30c19802aee
634aeaaa201a4c4fcf21e0920b1685243748f20e
1f4d72ea314b56d855fc9cde26ddcb0921538f92
9c34c177d7bf76c00cbc96132c569061ce6ca653
c257610c136376cf65c997a244fdc4966221258d
We cannot bisect more!

**Comment by pcercuei** [comment]
Thanks, I fixed it. Lightrec master triggers other failed assertions, I'll fix them and keep my Lightning local build with assertions enabled so that it won't happen again.

**Comment by pcercuei** [comment]
Latest master (1fecf77) should work without triggering assertions now.
