### ISSUE TITLE
Press reset on the console, Exception DSI crash

### ISSUE THREAD

**Issue by xjsxjs197** [pcercuei/lightrec#20]
Hi, dear pcercuei:

I don't know if this issue should be mentioned here. 
I also imported this very cool lightrec into the WiiStation(https://github.com/xjsxjs197/WiiSXRX_2022/).
Now, when press reset on the console, an exception occurred with DSI crash.
I'm trying to investigate and solve this problem, Basically confirm that have reached the following code branch.
vm.c
int vm_dsi_handler(u32 DSISR, u32 DAR)
{
	u16 v_index;
	u16 p_index;

	if (DAR<(u32)VM_Base || DAR>=0x80000000)
		// Maybe this point
	if ((DSISR&~0x02000000)!=0x40000000)
		// Maybe this point
.....
When press reset button, Is Virtual Memory mapping corrupted？
There's no clue at all. Can you help solve this issue ？

Thanks a lot.

**Comment by pcercuei** [comment]
It does work properly in WiiSX though. Just trace what functions are called when the reset button is pressed, and that should tell you what's going on.

Closing this, because it is not directly related to Lightrec.
