### ISSUE TITLE
MULT2 in gex 3

### ISSUE THREAD

**Issue by Jokippo** [pcercuei/lightrec#21]
The MULT2 conversion seems to cause Gex 3 to crash shortly after starting a new game on Wiistation. Removing the conversion makes it work again.

If I add a is_known check on both registers it seems to fix the crash. I don't know if that is right though.

Like so:

case OP_SPECIAL_MULTU:
				if (is_known(v, op->r.rs) && is_known(v, op->r.rt) &&
				    is_power_of_two(v[op->r.rs].value)) {
					tmp = op->c.i.rs;
					op->c.i.rs = op->c.i.rt;
					op->c.i.rt = tmp;
				} else if (!is_known(v, op->r.rt) || !is_known(v, op->r.rs) ||
					   !is_power_of_two(v[op->r.rt].value)) {
					break;
				}

**Comment by pcercuei** [comment]
Can't reproduce, with SLUS00806 on PC.

**Comment by Jokippo** [comment]
Might be Wiistation only then I guess, odd though.

**Comment by pcercuei** [comment]
@Jokippo I don't really trust Wiistation as it uses a very old version of PCSX with a lot of ugly hacks added on top.

Can you try to reproduce it with WiiSX from https://github.com/emukidid/pcsxgc/actions/runs/6023413694?

**Comment by pcercuei** [comment]
Ok I can reproduce it in WiiSX.
