### ISSUE TITLE
full bus access for sb sh

### ISSUE THREAD

**Issue by notaz** [pcercuei/lightrec#26]
It appears the r3000 puts the whole register on bus regardless if you write byte, half or full word. It's up to the receiving device to figure out what kind of write it is from the control signals. But apparently some hw registers don't look at the control signals at all and just latch the whole bus. There is at least scph7001 BIOS that relies on this behavior:
```
  lhu     $t9, 0($v1)  # v1 = 1f8010f0
  lui     $at, 0xFFF0
  ori     $at, $at, 0xFFFF
  and     $t0, $t9, $at 
  lui     $at, 8
  or      $t1, $t0, $at
  sh      $t1, 0($v1)
```
Lightrec's memhandlers seem to use u8 and u16 for data of sb and sh memhandlers respectively. My request is to have full u32 there.

**Comment by pcercuei** [comment]
I'll send a PR for PCSX' Lightrec glue tomorrow.
