### ISSUE TITLE
Power Rangers: Lightspeed Rescue (SLUS-01114) - Jump does not work adequately

### ISSUE THREAD

**Issue by saulfabregwiivc** [pcercuei/lightrec#27]
Not sure what makes this happen this issue but it seems this only affects on Lightrec, as Interpreter and other dynarecs can emulate the jump command adequately in this game **Power Rangers: Lightspeed Rescue** (SLUS-01114).

**Videos:**

latest PCSX-ReARMed https://github.com/libretro/pcsx_rearmed/commit/1f8c6be323aa8fad329e38682158197e822d27c1

https://github.com/pcercuei/lightrec/assets/66485640/42947342-755f-4c1e-9828-b0a7a2720e75

other dynarecs (yeah i know this is old PCSX-R but this is how the jump should work)

https://github.com/pcercuei/lightrec/assets/66485640/7a8f4383-ade6-4a10-8084-87331aca1236

**Comment by pcercuei** [comment]
I can reproduce the issue, but I can also reproduce it with PCSX' interpreter, so this is not a bug in Lightrec.

Please open this bug report in https://github.com/libretro/pcsx_rearmed instead.

**Comment by saulfabregwiivc** [comment]
Alright, thanks for the reply.
