### ISSUE TITLE
GPU Corruption in Duke Nukem Total Meltdown

### ISSUE THREAD

**Issue by ZachCook** [pcercuei/lightrec#6]
Mismatch!
CYCLE 0x5fd313aa PC 0x8008f578 CP0 0x7fbedad6 CP2D 0x3d7fe434 CP2C 0xe5c30193 INT 0x0804 INTCYCLE 0x2ebf30b4 GPU 0x5402200f GPR 0x0fcf30dc - Interpreter
CYCLE 0x5fd313aa PC 0x8008f578 CP0 0x7fbedad6 CP2D 0x3d7fe434 CP2C 0xe5c30193 INT 0x0804 INTCYCLE 0x2ebf30b4 GPU 0x54022112 GPR 0x0fcf30dc - Dynarec
State before the mismatch:
CYCLE 0x5fd31382 PC 0x80091a10 CP0 0x7fbedad6 CP2D 0x3d7fe434 CP2C 0xe5c30193 INT 0x0804 INTCYCLE 0x2ebf30b4 GPU 0x5402200f GPR 0xf675572e

**Comment by pcercuei** [comment]
What's the block at 0x80091a10?

**Comment by ZachCook** [comment]
DEBUG: Disassembled block at PC: 0x80091a10
	lui	v0,0x800b
	lw	v0,-6264(v0)
	nop
	lw	v0,0(v0)
	lui	v1,0x100
	and	v0,v0,v1
	bnez	v0,0x0000000030091a50
	nop
	lui	v0,0x800b
	lw	v0,-6276(v0)
	nop
	lw	v0,0(v0)
	lui	v1,0x400
	and	v0,v0,v1
	bnez	v0,0x0000000030091a5c
	move	v0,s0
	bnez	s0,0x0000000030091a5c
	move	v0,s0
	li	v0,1
	lw	ra,20(sp)
	lw	s0,16(sp)
	jr	ra
	addiu	sp,sp,24

**Comment by pcercuei** [comment]
Fixed, thanks.
