### ISSUE TITLE
dual licensing ?

### ISSUE THREAD

**Issue by barbudreadmon** [pcercuei/lightrec#7]
I have been thinking about porting this to [FBNeo](https://github.com/finalburnneo/FBNeo) and i was wondering if you would give authorization to use this under FBNeo's non-commercial license ? (we can't add GPL code to our codebase)

**Comment by pcercuei** [comment]
It's LGPL, so you can use it already, as long as you release any changes made to Lightrec itself.

**Comment by barbudreadmon** [comment]
Hmmmm, https://github.com/pcercuei/lightrec/blob/master/COPYING is pointing to GPLv2 though ?

**Comment by pcercuei** [comment]
"GNU LIBRARY GENERAL PUBLIC LICENSE" aka. LGPL.

**Comment by barbudreadmon** [comment]
Ok, sorry i was a bit confused because lgpl is "lesser general public license" for me. I never knew it had another name before lgpl-2.1.

**Comment by pcercuei** [comment]
Actually the COPYING file is wrong, it's the text for the LGPL-2.0 "Library GPL" license while Lightrec is licensed under the LGPL-2.1 "Lesser GPL". I'll update it.
