### ISSUE TITLE
Sync changes applied to rearmed and beetle?

### ISSUE THREAD

**Issue by ZachCook** [pcercuei/lightrec#9]
See: https://github.com/libretro/pcsx_rearmed/pull/530 and https://github.com/libretro/beetle-psx-libretro/pull/805

This doesn't help with games but does help for testing ports to new systems.

**Comment by pcercuei** [comment]
I'm not really OK with this change. It only updates the interpreter and not the emitter, which means there would be a behaviour difference between the two; and updating the emitter would result in much slower code. So unless there's a game that breaks because of this, I'd prefer not having these.
